### ISSUE TITLE
HU2: Yo como usuaria quiero tomar nota para no depender de mi mala memoria y tener presente en todo momento los apuntes o cosas importantes que antes escribía en papel

### ISSUE THREAD

**Issue by Melissa-Bracamonte** [Melissa-Bracamonte/CDMX012-notes#2]
Definición de terminado

- [ ] Las notas se almacenan en una colección en firestore
- [ ] Haber recibido code review de una compañera
- [ ] Test unitarios
- [ ] Testeo manual
- [ ] Etiquetar versión (git tag)
- [ ] Que sea responsive
- [ ] La página cuenta con el mismo diseño que el prototipo de alta fidelidad
- [ ] Es una SPA
- [ ] Test de usabilidad

Criterios de aceptación
- [ ] Anotar un título a mi nota
- [ ] Agregar el contenido de mi nota.
- [ ] Tengo un botón de "crear nota"
- [ ] Mis notas se muestren en pantalla
- [ ] Puede visualizar la pagina desde tablet y móvil
